import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open } from "@tauri-apps/plugin-dialog";
import { openPath } from "@tauri-apps/plugin-opener";
import { Check, ChevronRight, FileSpreadsheet, FileText, FolderOpen, Moon, Play, RotateCcw, Settings as SettingsIcon, Sun, X } from "lucide-react";
import type { DataPreview, GenerateResult, Settings } from "./types";

const defaults: Settings = { outputFormat: "word", outputMethod: "folder", addSerialNumber: true, serialDigits: 2, formatAmountWithComma: true, rowExcludeMode: "selected_column_number_empty", targetColumnNumber: 2, filenameKeys: ["名前（漢字）"] };
const loadSettings=():Settings=>{try{return {...defaults,...JSON.parse(localStorage.getItem("wordBatchSettings")||"{}")}}catch{return defaults}};

function Segmented<T extends string>({value,onChange,items}:{value:T;onChange:(v:T)=>void;items:{value:T;label:string}[]}){return <div className="segmented">{items.map(i=><button key={i.value} className={value===i.value?"active":""} onClick={()=>onChange(i.value)}>{i.label}</button>)}</div>}
function Picker({kind,title,path,meta,onPick}:{kind:"word"|"excel"|"folder";title:string;path:string;meta?:string;onPick:()=>void}){const Icon=kind==="word"?FileText:kind==="excel"?FileSpreadsheet:FolderOpen;return <button className="picker" onClick={onPick}><span className="picker-icon"><Icon size={20}/></span><span className="picker-body"><small>{title}</small><strong>{path?path.split(/[\\/]/).pop():"クリックして選択"}</strong><span>{meta||(!path?"ドラッグ＆ドロップ対応予定":"選択済み")}</span></span><span className="change">{path?"変更":"選択"}</span></button>}

export default function App(){
 const [dark,setDark]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[previewOpen,setPreviewOpen]=useState(false);
 const [templatePath,setTemplatePath]=useState(""),[dataPath,setDataPath]=useState(""),[outputPath,setOutputPath]=useState("");
 const [preview,setPreview]=useState<DataPreview|null>(null),[settings,setSettings]=useState<Settings>(loadSettings),[busy,setBusy]=useState(false),[status,setStatus]=useState("準備完了"),[result,setResult]=useState<GenerateResult|null>(null),[error,setError]=useState("");
 useEffect(()=>{localStorage.setItem("wordBatchSettings",JSON.stringify(settings))},[settings]);
 const canRun=!!templatePath&&!!dataPath&&!!outputPath&&!!preview?.included_count&&!busy;
 const exampleName=useMemo(()=>{const row=preview?.included_rows[0];const parts=[] as string[];if(settings.addSerialNumber)parts.push(String(1).padStart(settings.serialDigits,"0"));for(const key of settings.filenameKeys){const v=row?.[key]?.trim();if(v)parts.push(v.replace(/\s+/g," "))}parts.push((templatePath.split(/[\\/]/).pop()||"テンプレート.docx").replace(/\.docx$/i,settings.outputFormat==="pdf"?".pdf":".docx"));return parts.join("_")},[preview,settings,templatePath]);
 async function chooseTemplate(){const p=await open({multiple:false,filters:[{name:"Word",extensions:["docx"]}]});if(typeof p==="string"){setTemplatePath(p);setResult(null)}}
 async function chooseData(){const p=await open({multiple:false,filters:[{name:"置換データ",extensions:["xlsx","xlsm","xls","csv"]}]});if(typeof p==="string"){setDataPath(p);setResult(null);await inspect(p)}}
 async function chooseOutput(){const p=await open({directory:true,multiple:false});if(typeof p==="string"){setOutputPath(p);setResult(null)}}
 async function inspect(path=dataPath){if(!path)return;setBusy(true);setError("");setStatus("置換データを確認しています...");try{const r=await invoke<DataPreview>("inspect_data",{request:{data_path:path,format_amount_with_comma:settings.formatAmountWithComma,row_exclude_mode:settings.rowExcludeMode,row_exclude_target_column_number:settings.targetColumnNumber}});setPreview(r);setStatus(`使用${r.included_count}件・除外${r.excluded_count}件`)}catch(e){setPreview(null);setError(String(e));setStatus("読込エラー")}finally{setBusy(false)}}
 async function generate(){if(!canRun)return;setBusy(true);setError("");setResult(null);setStatus("Wordファイルを作成しています...");try{const r=await invoke<GenerateResult>("generate_documents",{request:{template_path:templatePath,data_path:dataPath,output_path:outputPath,filename_keys:settings.filenameKeys,add_serial_number:settings.addSerialNumber,serial_digits:settings.serialDigits,format_amount_with_comma:settings.formatAmountWithComma,row_exclude_mode:settings.rowExcludeMode,row_exclude_target_column_number:settings.targetColumnNumber}});setResult(r);setStatus("完了")}catch(e){setError(String(e));setStatus("処理エラー")}finally{setBusy(false)}}
 return <div className={dark?"app dark":"app"}>
  <header><div><h1>Wordファイル一括作成</h1><p>テンプレートと置換データから文書をまとめて作成します。</p></div><div className="header-actions"><button className="icon-button" onClick={()=>setDark(v=>!v)} aria-label="テーマ切替">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button" onClick={()=>setSettingsOpen(true)} aria-label="設定"><SettingsIcon size={18}/></button></div></header>
  <main>
   <section className="picker-grid"><Picker kind="word" title="テンプレート" path={templatePath} onPick={chooseTemplate}/><Picker kind="excel" title="置換データ" path={dataPath} meta={preview?`使用${preview.included_count}件・除外${preview.excluded_count}件`:undefined} onPick={chooseData}/></section>
   {preview&&<button className="preview-link" onClick={()=>setPreviewOpen(true)}><span><strong>置換データを確認</strong><small>読込{preview.original_count}件、使用{preview.included_count}件、除外{preview.excluded_count}件</small></span><ChevronRight size={18}/></button>}
   <Picker kind="folder" title="出力先" path={outputPath} onPick={chooseOutput}/>
   <section className="options-card"><div><label>出力形式</label><Segmented value={settings.outputFormat} onChange={v=>setSettings(s=>({...s,outputFormat:v}))} items={[{value:"word",label:"Word"}]}/><small className="later">PDFは次段階で対応</small></div><div><label>出力方法</label><Segmented value={settings.outputMethod} onChange={v=>setSettings(s=>({...s,outputMethod:v}))} items={[{value:"folder",label:"個別"}]}/><small className="later">結合・ZIPは次段階で対応</small></div><button className="details" onClick={()=>setSettingsOpen(true)}>ファイル名と詳細設定<ChevronRight size={17}/></button></section>
   {exampleName&&<section className="filename"><small>出力ファイル名の例</small><code>{exampleName}</code></section>}
   {error&&<section className="error"><strong>処理できませんでした</strong><p>{error}</p><button onClick={()=>dataPath&&inspect()}>再読み込み</button></section>}
   {result?<section className="success"><span><Check size={18}/></span><div><strong>{result.generated_count}件のWordファイルを作成しました</strong><p>{result.output_path}</p><div><button className="primary" onClick={()=>openPath(result.output_path)}><FolderOpen size={16}/>出力先を開く</button><button onClick={()=>{setResult(null);setStatus("準備完了")}}><RotateCcw size={16}/>新しく作成</button></div></div></section>:<section className="runbar"><div><strong>{preview?.included_count||0}件</strong>のWordファイルを作成します<small>{status}</small></div><button className="primary" disabled={!canRun} onClick={generate}><Play size={16}/>{busy?"処理中...":"複製を開始"}</button></section>}
  </main>
  {settingsOpen&&<div className="overlay" onMouseDown={()=>setSettingsOpen(false)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><h2>詳細設定</h2><p>変更内容は自動保存されます。</p></div><button className="icon-button" onClick={()=>setSettingsOpen(false)}><X size={18}/></button></div><div className="drawer-body"><h3>ファイル名</h3><label className="check"><input type="checkbox" checked={settings.addSerialNumber} onChange={e=>setSettings(s=>({...s,addSerialNumber:e.target.checked}))}/>先頭に通し番号を付ける</label><label>桁数<input type="number" min="1" max="6" value={settings.serialDigits} onChange={e=>setSettings(s=>({...s,serialDigits:Number(e.target.value)}))}/></label><h3>行の除外</h3><label>条件<select value={settings.rowExcludeMode} onChange={e=>setSettings(s=>({...s,rowExcludeMode:e.target.value as Settings["rowExcludeMode"]}))}><option value="any_empty_except_first">1列目以外に空欄があれば除外</option><option value="any_empty">どこかに空欄があれば除外</option><option value="all_empty_except_first">1列目以外がすべて空なら除外</option><option value="selected_column_number_empty">指定列が空なら除外</option></select></label><label>指定列番号<input type="number" min="1" value={settings.targetColumnNumber} onChange={e=>setSettings(s=>({...s,targetColumnNumber:Number(e.target.value)}))}/></label><h3>金額</h3><label className="check"><input type="checkbox" checked={settings.formatAmountWithComma} onChange={e=>setSettings(s=>({...s,formatAmountWithComma:e.target.checked}))}/>金額を3桁区切りにする</label><button className="primary full" onClick={async()=>{setSettingsOpen(false);if(dataPath)await inspect()}}>設定を適用</button></div></aside></div>}
  {previewOpen&&preview&&<div className="overlay" onMouseDown={()=>setPreviewOpen(false)}><section className="preview-modal" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><h2>置換データの確認</h2><p>使用{preview.included_count}件・除外{preview.excluded_count}件・記入例{preview.example_count}件</p></div><button className="icon-button" onClick={()=>setPreviewOpen(false)}><X size={18}/></button></div><div className="table-wrap"><table><thead><tr>{preview.columns.slice(0,6).map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{preview.included_rows.map((r,i)=><tr key={i}>{preview.columns.slice(0,6).map(c=><td key={c}>{r[c]}</td>)}</tr>)}</tbody></table></div></section></div>}
 </div>
}
